services:
  revers-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    container_name: revers-proxy
    volumes:
      - ./nginx:/etc/nginx:ro 
    restart: unless-stopped
    networks:
      - proxy-back   

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy-back

networks:
  proxy-back:
    driver: bridge